boring

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -27,22 +27,22 @@ jobs:
         FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
       run: |
         echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
-        ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
+        ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} << EOF
           set -x
-          echo "Project path: $PROJECT_PATH"
-          sudo chmod 666 /run/docker.sock
-          cd $PROJECT_PATH || exit 1
+          echo "Project path: \$PROJECT_PATH"
+          sudo -n chmod 666 /run/docker.sock || echo "Failed to change Docker socket permissions"
+          cd \$PROJECT_PATH || exit 1
           git pull origin main
           /snap/bin/docker build \
-            --build-arg VITE_FIREBASE_API_KEY='"'"''"$FIREBASE_API_KEY"''"'"' \
-            --build-arg VITE_FIREBASE_AUTH_DOMAIN='"'"''"$FIREBASE_AUTH_DOMAIN"''"'"' \
-            --build-arg VITE_FIREBASE_PROJECT_ID='"'"''"$FIREBASE_PROJECT_ID"''"'"' \
-            --build-arg VITE_FIREBASE_STORAGE_BUCKET='"'"''"$FIREBASE_STORAGE_BUCKET"''"'"' \
-            --build-arg VITE_FIREBASE_MESSAGING_SENDER_ID='"'"''"$FIREBASE_MESSAGING_SENDER_ID"''"'"' \
-            --build-arg VITE_FIREBASE_APP_ID='"'"''"$FIREBASE_APP_ID"''"'"' \
-            --build-arg VITE_FIREBASE_MEASUREMENT_ID='"'"''"$FIREBASE_MEASUREMENT_ID"''"'"' \
+            --build-arg VITE_FIREBASE_API_KEY="\${FIREBASE_API_KEY}" \
+            --build-arg VITE_FIREBASE_AUTH_DOMAIN="\${FIREBASE_AUTH_DOMAIN}" \
+            --build-arg VITE_FIREBASE_PROJECT_ID="\${FIREBASE_PROJECT_ID}" \
+            --build-arg VITE_FIREBASE_STORAGE_BUCKET="\${FIREBASE_STORAGE_BUCKET}" \
+            --build-arg VITE_FIREBASE_MESSAGING_SENDER_ID="\${FIREBASE_MESSAGING_SENDER_ID}" \
+            --build-arg VITE_FIREBASE_APP_ID="\${FIREBASE_APP_ID}" \
+            --build-arg VITE_FIREBASE_MEASUREMENT_ID="\${FIREBASE_MEASUREMENT_ID}" \
             -t workshop-management .
           /snap/bin/docker stop workshop-container || true
           /snap/bin/docker rm -f workshop-container || true
-          /snap/bin/docker run -d --name workshop-container -p 80:80 workshop-management
-        '
+          /snap/bin/docker run -d --name workshop-container -p 80:3000 workshop-managemen
+EOF
